baseURL = "https://neverfapdeluxe.netlify.com/"
languageCode = "en-us"
title = "NeverFap Deluxe: How to overcome porn addiction without killing yourself"
theme = "deluxe_theme"

enableRobotsTXT = true
canonifyURLs = true
googleAnalytics = "UA-132863786-1"

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
    post = "/guide/:slug"


