baseURL = "https://neverfapdeluxe.com/"
languageCode = "en-us"
theme = "deluxe_theme"

enableRobotsTXT = true
canonifyURLs = true
googleAnalytics = "UA-132863786-1"

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
    post = "/guide/:slug"

[author]
  name = "Julius Reade"

[params]
  author = "Julius Reade"
  title = "NeverFap Deluxe | The World's Most Comprehensive Porn Addiction Recovery Solution."
  description = "NeverFap Deluxe | The World's Most Comprehensive Porn Addiction Recovery Solution."
