# baseURL = "https://neverfapdeluxe.com/"
baseURL = "https://jovial-mccarthy-89fca4.netlify.com/"
languageCode = "en-us"
title = "NeverFap Deluxe: How to overcome porn addiction without killing yourself"
theme = "deluxe_theme"

enableRobotsTXT = true
canonifyURLs = true
googleAnalytics = "UA-123-45"

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
    post = "/guide/:slug"


